### ISSUE TITLE
Respect Terrain Height?

### ISSUE THREAD

**Issue by benmarten** [algernon-A/ImageOverlay#1]
I'm trying to create a new map with the new map editor, but the image overlay is cut off by higher terrain areas.

Is there a way to have the mod respect the map terrain, or alternatively add a setting to align the height of the overlay? Thx!

**Comment by algernon-A** [comment]
Projecting the overlay onto the terrain is planned, but is not a trivial task (and may not be able to happen due to the challenges involved).

You can change the elevation of the overlay by using the elevation change keys mentioned on the README, or by using the slider in the mod's options panel.
